# -*- coding: utf-8 -*-
"""linear_regression.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1CmGVOlFH3JpH-7x8ugHoP9OAguOvnUCm
"""

import numpy as np
import pandas as pd
import os
data=pd.read_csv("FuelConsumption.csv")
data.head(10)
data.info()
data.describe()
import matplotlib.pyplot as plt
import seaborn as sns
df = data[['ENGINE SIZE','CYLINDERS','FUEL CONSUMPTION','COEMISSIONS ']]
df.hist(color='red')
plt.show()
from sklearn.linear_model import LinearRegression
from sklearn.metrics import r2_score
from sklearn.model_selection import train_test_split
model=LinearRegression()
x=data[['ENGINE SIZE','CYLINDERS','FUEL CONSUMPTION']]
y=data[['COEMISSIONS ']]
xtrain, xtest, ytrain, ytest = train_test_split(x,y, test_size = 0.2,random_state=42)
model.fit(xtrain,ytrain)
pre=model.predict(xtest)
r2score=r2_score(ytest,pre)
print("Accuracy of linear regression is::",r2score*100,"%")